import { AlertTriangle, Check, ChevronLeft, ChevronRight, Flame, ShieldAlert, VolumeX } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useEffect, useMemo, useState } from "react";

type HistoryPoint = { time: string; temperature: number; precipitation: number; wind: number };
type Thresholds = { rainRate: number; hail: number; lightning: number; wind: number };
type AlertState = { acknowledged: boolean; mutedUntil: number; escalation: number };
type Props = { cellId: number; date: string; maxDate: string; hour: number; history: { status: string; points: HistoryPoint[]; message: string }; thresholds: Thresholds; alarmsEnabled: boolean; activeAlerts: string[]; alertLog: string[]; historyOpen: boolean; onToggleHistory: () => void; onDateChange: (value: string) => void; onHourChange: (value: number) => void; onThresholdChange: (key: keyof Thresholds, value: number) => void; onToggleAlarms: () => void; onEnableNotifications: () => void };

const emptyState: AlertState = { acknowledged: false, mutedUntil: 0, escalation: 0 };
const keyFor = (label: string) => `vajra-alert:${label}`;

export function TelemetryPanels({ cellId, date, maxDate, hour, history, thresholds, alarmsEnabled, activeAlerts, alertLog, historyOpen, onToggleHistory, onDateChange, onHourChange, onThresholdChange, onToggleAlarms, onEnableNotifications }: Props) {
  const [states, setStates] = useState<Record<string, AlertState>>({});
  const [muteMenu, setMuteMenu] = useState<string | null>(null);
  const [, tick] = useState(0);
  useEffect(() => { const saved = localStorage.getItem("vajra-alert-states"); if (saved) setStates(JSON.parse(saved)); }, []);
  useEffect(() => { localStorage.setItem("vajra-alert-states", JSON.stringify(states)); }, [states]);
  useEffect(() => { const timer = window.setInterval(() => tick((value) => value + 1), 30000); return () => window.clearInterval(timer); }, []);
  const setAlertState = (label: string, patch: Partial<AlertState>) => setStates((current) => ({ ...current, [keyFor(label)]: { ...emptyState, ...current[keyFor(label)], ...patch } }));
  const mute = (label: string, minutes: number) => { setAlertState(label, { mutedUntil: Date.now() + minutes * 60000 }); setMuteMenu(null); };
  const escalate = (label: string) => setAlertState(label, { escalation: Math.min(2, (states[keyFor(label)]?.escalation ?? 0) + 1), acknowledged: false });
  const escalationLabel = (level: number) => ["OPERATOR", "SUPERVISOR", "EMERGENCY"][level] ?? "OPERATOR";
  const activeStates = useMemo(() => activeAlerts.map((label) => ({ label, state: states[keyFor(label)] ?? emptyState })).filter(({ state }) => state.mutedUntil <= Date.now()), [activeAlerts, states]);
  return <>
    <section className={`glass-panel history-panel ${historyOpen ? "" : "collapsed-panel"}`}><div className="panel-kicker"><span>05 / HISTORICAL CELL PLAYBACK</span><span className={history.status === "live" ? "telemetry-live" : "telemetry-error"}><span /> {history.status === "live" ? "ARCHIVE LINKED" : history.status.toUpperCase()}</span><button className="panel-collapse" aria-label={historyOpen ? "Collapse historical playback" : "Expand historical playback"} onClick={onToggleHistory}>{historyOpen ? "−" : "+"}</button></div>{historyOpen && <><div className="history-head"><div><h2>Grid #{cellId}_88 <span>· {date}</span></h2><p>{history.message} · Open-Meteo ERA5 / hourly · OBSERVED ARCHIVE, NOT ML</p></div><div className="history-controls"><input aria-label="Historical date" type="date" max={maxDate} value={date} onChange={(event) => onDateChange(event.target.value)} /><button aria-label="Previous historical hour" onClick={() => onHourChange(Math.max(0, hour - 1))}><ChevronLeft size={13} /></button><b>{String(hour).padStart(2, "0")}:00Z</b><button aria-label="Next historical hour" onClick={() => onHourChange(Math.min(23, hour + 1))}><ChevronRight size={13} /></button></div></div><div className="history-chart">{history.points.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={history.points}><CartesianGrid stroke="rgba(148,163,184,.12)" vertical={false} /><XAxis dataKey="time" tickFormatter={(value) => String(value).slice(11, 13)} tick={{ fill: "#658196", fontSize: 8 }} axisLine={false} tickLine={false} /><YAxis yAxisId="temp" tick={{ fill: "#658196", fontSize: 8 }} axisLine={false} tickLine={false} width={26} /><YAxis yAxisId="rain" orientation="right" hide domain={[0, "auto"]} /><Tooltip contentStyle={{ background: "#08121e", border: "1px solid rgba(56,189,248,.4)", color: "#dbeaf4", fontSize: 10 }} labelFormatter={(value) => `${String(value).slice(11, 16)}Z`} /><Line yAxisId="temp" type="monotone" dataKey="temperature" stroke="#38bdf8" strokeWidth={2} dot={false} /><Line yAxisId="rain" type="monotone" dataKey="precipitation" stroke="#ef817d" strokeWidth={1.5} dot={false} /></LineChart></ResponsiveContainer> : <div className="history-empty">{history.status === "loading" ? "FETCHING HOURLY ARCHIVE…" : "HISTORICAL SERIES UNAVAILABLE"}</div>}</div><div className="history-legend"><span><i className="legend-temp" /> TEMPERATURE °C</span><span><i className="legend-rain" /> PRECIPITATION MM</span></div></>}</section>
    <section className="glass-panel alarm-panel"><div className="panel-kicker"><span>06 / SEVERE WEATHER ALARMS</span><button className={`alarm-toggle ${alarmsEnabled ? "active" : ""}`} onClick={onToggleAlarms}><span /> {alarmsEnabled ? "ARMED" : "MUTED"}</button></div><div className="alarm-grid"><label>RAIN RATE <input type="number" min="1" value={thresholds.rainRate} onChange={(event) => onThresholdChange("rainRate", Number(event.target.value))} /><small>MM/HR</small></label><label>HAIL PROB. <input type="number" min="1" max="100" value={thresholds.hail} onChange={(event) => onThresholdChange("hail", Number(event.target.value))} /><small>%</small></label><label>LIGHTNING <input type="number" min="1" value={thresholds.lightning} onChange={(event) => onThresholdChange("lightning", Number(event.target.value))} /><small>/KM²/10M</small></label><label>WIND GUST <input type="number" min="1" value={thresholds.wind} onChange={(event) => onThresholdChange("wind", Number(event.target.value))} /><small>KM/H</small></label></div><div className="alarm-events">{activeAlerts.length ? activeAlerts.map((label) => { const state = states[keyFor(label)] ?? emptyState; const remaining = Math.max(0, state.mutedUntil - Date.now()); return <div className={`alarm-event ${state.acknowledged ? "acknowledged" : ""}`} key={label}><div><AlertTriangle size={12} /><b>{label}</b><small>{state.acknowledged ? "ACKNOWLEDGED" : `ESCALATION: ${escalationLabel(state.escalation)}`}{remaining ? ` · MUTED ${Math.ceil(remaining / 60000)}M` : ""}</small></div><div className="alarm-actions"><button title="Acknowledge alert" onClick={() => setAlertState(label, { acknowledged: true })}><Check size={12} /> ACK</button><button title="Mute alert" onClick={() => setMuteMenu(muteMenu === label ? null : label)}><VolumeX size={12} /> MUTE</button><button title="Escalate alert" onClick={() => escalate(label)}><Flame size={12} /> ESCALATE</button>{muteMenu === label && <div className="mute-menu"><button onClick={() => mute(label, 15)}>15 MIN</button><button onClick={() => mute(label, 60)}>1 HOUR</button><button onClick={() => mute(label, 240)}>4 HOURS</button><button onClick={() => mute(label, Math.max(1, Math.ceil((new Date().setHours(23, 59, 59, 999) - Date.now()) / 60000)))}>END OF DAY</button></div>}</div></div>; }) : <div className="alarm-empty"><ShieldAlert size={14} /> NO THRESHOLD TRIGGERS</div>}</div><div className="alarm-footer"><span className={activeStates.length ? "alarm-triggered" : ""}><AlertTriangle size={12} /> {activeStates.length} ACTIVE / {activeAlerts.length} TOTAL</span><button onClick={onEnableNotifications}>ENABLE BROWSER NOTIFICATIONS</button><small>{alertLog.length ? "RECENT EVENT LOGGED · STATE SAVED LOCALLY" : "EVENT LOG CLEAR"}</small></div></section>
  </>;
}
